### ISSUE TITLE
[Frontend] Popolare un database fake di 25 interventi

### ISSUE THREAD

**Issue by supix** [vvfosprojects/sovvf#21]
Ai fini della _Seconda Demo_ è utile popolare un database di interventi fake ben assortiti (diverse tipologie, diverse priorità, diverse zone di competenza). Il database sarà formato da 25 interventi di cui 17 chiusi.

**Comment by cicarulez** [comment]
Creare anche un fake di eventorichieste, collegato ad una delle richieste.
Creare anche il fake dei markers delle richieste e dei mezzi per le richieste di soccorso, presidiate, in rientro etc...
