### ISSUE TITLE
[Backend] [Frontend] Reperimento ruoli utente loggato

### ISSUE THREAD

**Issue by cicarulez** [vvfosprojects/sovvf#81]
## Comportamento atteso
All'avvio dell'applicazione, viene effettuata una chiamata al back-end per il reperimento dei ruoli dell'utente loggato. I ruoli vengono salvati nella session storage e disponibili per l'intera sessione di lavoro. Le eventuali modifiche dei ruoli vengono notificate con SignalR

## Comportamento attuale
All'avvio l'applicazione, fa riferimento ai ruoli salvati nella local storage e memorizzati al momento della login.

## Possibili soluzioni
Creare un nuovo metodo backend, ad esempio getRuoliById ed implementare un servizio rest lato client che viene interrogato ogni volta che l'applicazione si avvia, e i dati relativi al ruolo dell'utente vengono memorizzati nella session storage.

**Comment by Furgoncino** [comment]
Il BE restituisce i ruoli dell'utente loggato nella Navbar. Da testare con il FE.
